### ISSUE TITLE
Unable to create a dummy server without using config file for resources declaration

### ISSUE THREAD

**Issue by aleixmorgadas** [vlingo/vlingo-http#1]
Looking in the [tests for usage examples][server-test] and I found that [it uses](resource-test) the class [Resources][resources-class].

Because `Resources` class is package-private, seems like the only way to add the Resources is via [configuration-file][config]. Is it the desired design? Did I miss something?

I miss a DSL to create the Resources via code instead of config file.

[server-test]: https://github.com/vlingo/vlingo-http/blob/master/src/test/java/io/vlingo/http/resource/ServerTest.java#L109
[resource-test]: https://github.com/vlingo/vlingo-http/blob/master/src/test/java/io/vlingo/http/resource/ResourceTestFixtures.java#L156
[resources-class]: https://github.com/vlingo/vlingo-http/blob/master/src/main/java/io/vlingo/http/resource/Resources.java#L31
[config]: https://github.com/vlingo/vlingo-http/blob/master/src/test/resources/vlingo-http.properties#L22-L71

**Comment by aleixmorgadas** [comment]
I would like to contribute on the DSL to create `Resources` instead of using configuration files. I've seen you haven't a `CONTRIBUTING.md` file with the contribution guidelines. Should I do Fork & PR?

**Comment by VaughnVernon** [comment]
If you wish to discuss, you can present a gist. Otherwise we can work through a PR. I suggest that you look at vlingo-http Request fluent API for building a Request as a hint on what I would like to see (actually gives two APIs, with more and less expensiveness).

**Comment by aleixmorgadas** [comment]
I share the first design steps I made regarding the DSL. I would like it to be 100% code driven without String references.

```java
public class Application {

    public static void main(String[] args) {
        final World world = World.start("http example");
        Server.startWith(
                world.stage(),
                Resources.are(Application.resource()),
                8000,
                new Server.Sizing(10, 100, 65444),
                new Server.Timing(10, 100, 1000)
                );
    }

    private static Resource<?> resource() {
        return route("user")
                .withHandlerPoolSize(10)
                .get("/helloworld", (request -> Response.of(Ok, serialized("Hello world"))))
                .build();
    }
}
```

Check PR #3 for details.

**Comment by VaughnVernon** [comment]
@aleixmorgadas I think you have accomplished your goal. I don't know how you would eliminate the strings that you use in the above code, and hopefully that's not your goal :)

**Comment by aleixmorgadas** [comment]
Yes :) I will be able to iterate over that DSL and no, my goal isn't remove the remaining strings ;)

**Comment by aleixmorgadas** [comment]
closing this one in favour of #5
