### ISSUE TITLE
Feature: Optional Mapper

### ISSUE THREAD

**Issue by aleixmorgadas** [vlingo/vlingo-http#14]
### abstract

Fluent API should accept Mappers for scoped resources or specific endpoint.

## specification

The user should be able to specify a concrete Mapper for
- [ ] Resources
- [x] Resource Handler

**Comment by VaughnVernon** [comment]
@brian-wehrle-roche If you are willing to work on this I think it would be fairly straightforward.

The chain starts at `ResourceBuilder` but your changes would be in `RequestHandler0` - `RequestHandler4`. You would need to follow the pattern in these five classes and add the following:

`public <T extends Mapper> RequestHandler1<T> mapper(final Class<T> mapperClass) { ... }` 

to each of the classes `RequestHandler0` - `RequestHandler4`. Look at how each of those classes implement the `body(...)` method and it would be very similar. 

When this is accomplished you should be able to create and expression like this:

`post("/foo").body(Bar.class).mapper(BarDataMapper.class).handle(this::createFoo)`

From there you can create your own `Mapper` such as the one found in the `vlingo-http/src/test/` class `io.vlingo.http.sample.user.ProfileDataMapper`.  To implement a type-safe `Mapper` you will need some sort of non-null assertions after the body is mapped into the type. Inside `BarDataMapper`:

if (bar.val == 0) throw new IllegalStateException("The body data mapping to Bar is invalid: " + bar);

I hope that helps.

**Comment by aleixmorgadas** [comment]
There’re different options.

1. `post("/foo").body(Bar.class).mapper(BarDataMapper.class).handler(…)`
2. `post("/foo").body(Bar.class, BarDataMapper.class).handler(…)`

I think the 2. option is more clear that's for that body class. Also, you can use generics that are related with each other, in the 1. case you cannot really infer which is the body type because of how it's designed the `ResourceHandler0..5`.

Also, could it be useful to be implemented at resource level?

_example, syntax not definitive_

```java
return resource("foo bar", 
    with(BarDataMapper.class), 
    post("/foo").body(Bar.class).handler(…));
```

**Comment by aleixmorgadas** [comment]
> Unless you are expecting the method to instantiate an instance via the Class reference, I think it needs to be changed.

I've not a strong opinion one vs the other. When using configuration based, it creates an instance though class reference as you mentioned instead of receiving an instance.

In FluentAPI, we could simply pass an instance.

```java
public <T> RequestHandler1<T> body(final Class<T> paramClass, final Mapper mapper) {...}
```

You might found that [PathResolver](https://github.com/vlingo/vlingo-http/blob/master/src/main/java/io/vlingo/http/resource/ParameterResolver.java#L34-L37) has that method already implemented.

**Comment by VaughnVernon** [comment]
@brian-wehrle-roche Great work! @aleixmorgadas Is this ready to close?

**Comment by bwehrle** [comment]
Hi @aleixmorgadas , @VaughnVernon,
I don't think these are related issues.  I actually experienced this hang in two distinct cases:
(1) empty response or (2) an exception in the "Resource" class, though the latter could lead to the former.
Regards,
Brian

**Comment by aleixmorgadas** [comment]
> Great work! @aleixmorgadas Is this ready to close?

Yes, I will move the `Resource Handler` definition into a new issue. Since it's not 100% related to Object Mapping. I will detail there what I've in mind and see if it makes sense now or not :smile:
