### ISSUE TITLE
Generic  exception handling support

### ISSUE THREAD

**Issue by bwehrle** [vlingo/vlingo-http#24]
Hi @aleixmorgadas,
When an  actor throws an exception, the  resource  code bails and the client code hangs.  This is easy to repo by putting a throw or NPE into the actor code.  I  propose that the Resource handling system support new behavior such that I can add in to manage  exceptional cases or where exceptions can be handled... This is where an IllegalStateException could be turned into a 404  response  generically for  different routes.

For example:
````
post( url ).body( RequestData.class  ).errorHandler(  errorHandler   ); 
````

**Comment by aleixmorgadas** [comment]
Hi @bwehrle,

I see the value on the `errorHandler` method. Which is the signature do you propose? Something like `errorHandler(final Function<Throwable, Response> errorHandlerFunction)`?

**Comment by bwehrle** [comment]
Hi Aleix,

That sounds like a good idea for the signature.    Let me take a look  at
implementing this and  send you a PR-  hopefully it will be useful to
others  as well.

The other idea I had was smartly  setting the the content-type header.
Currently the header is not  set smartly, meaning, the mapper knows  the
output format  but does not  set the header appropriately.
This  would be easy to change and add to the mapper interface.  When
writing my tests using RestAssured I noticed that the  Content-Type header
was not being set (it complains when it finds these situation).

Regards,
Brian

**Comment by bwehrle** [comment]
I created a PR for this feature request.  Please take a look at and the notes for feedback.
https://github.com/vlingo/vlingo-http/pull/27
Regards,
Brian

**Comment by bwehrle** [comment]
I believe we can close this issue now since the following PRs have been merged:
https://github.com/vlingo/vlingo-http/pull/27
https://github.com/vlingo/vlingo-http/pull/31
