### ISSUE TITLE
Smart Content-Type header

### ISSUE THREAD

**Issue by ghost** [vlingo/vlingo-http#26]
@bwehrle said on #24:

>The other idea I had was smartly setting the the content-type header. Currently the header is not set smartly, meaning, the mapper knows the output format but does not set the header appropriately. This would be easy to change and add to the mapper interface. When writing my tests using RestAssured I noticed that the Content-Type header was not being set (it complains when it finds these situation).

### Feature

Smart Content-Type based on Mapping interfeace.

### Further discussion

Should we have fluent mapping depending on requested `Content-Type`? Example:

Same endpoint:
- `Content-Type: application/json` → use Gson mapper instance
- `Content-Type: application/xml` → use another mapper instance
- undefined `Content-Type` → json as default mapper instance

Does it make sense?

**Comment by VaughnVernon** [comment]
May I suggest adding a new method rather than changing the current one?

**Comment by bwehrle** [comment]
Sure,  a backwards compatible option to not break existing users of the
current API-  this is a requirement as well. Next time I'll use more
specific language when describing the proposed change.  Hopefully this
weekend I can work on this.
Regards,
Brian

**Comment by VaughnVernon** [comment]
@aleixmorgadas @bwehrle I think we can close this issue as Brian has completed the feature and I created docs from Brian's usage description. Agree?

**Comment by VaughnVernon** [comment]
@kmruiz Do you think that this issue's resolution supports issue #29 that you created? If so, can you close #29 as fixed by #26? Thanks!

**Comment by kmruiz** [comment]
It supports most of the features so I can close #29 and if we find out that we need more advanced subclassing we can create a new one.
